### ISSUE TITLE
2-level File structure?

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/Textbook#10]
With the new build system, the file hierarchy is reflected directly within the URL. I propose we attempt to keep the URL as short as possible. Maybe that would be a max 2-level deep repo for main pages? and max 3 for resources? Example: aguaclara.github.io/Textbook/section/page  Therefore we take everything out of the "Aguaclara water treatment plant design" folder. Thoughts on this? Is this enough to do what we want? images could be at: aguaclara.github.io/Textbook/section/images/image @juanchon998 @clare45 @monroews

**Comment by juanchon998** [comment]
Done!
