### ISSUE TITLE
Add PDF and Latex output to the site

### ISSUE THREAD

**Issue by eak24** [AguaClara/Textbook#17]
After discussing this with Monroe and Juan, we decided it would be useful to have a PDF and Latex version of the textbook. I've investigated this for a few hours, and have come to the conclusion that the best looking PDF comes out of running `make pdflatex` (which is a Sphinx command that builds a latex document whose intention is to be converted to PDF) and then use [Tectonic](https://github.com/tectonic-typesetting/tectonic), which is a self contained tex engine that generates a PDF. I plan to use Travis with a conditional deploy to "Github Releases" that deploys both the tex files in a zip and the pdf to the particular tagged version of the website. Then, we'll offer a link that updates with the Github tag number to point to the correct release.

**Comment by ethan92429** [comment]
Here's an example PDF of the current site made through this process.
[AguaClaraTextbook.pdf](https://github.com/AguaClara/Textbook/files/2143264/AguaClaraTextbook.pdf)

**Comment by ethan92429** [comment]
@juanchon998 @clare45 let me know if there's anything you'd like to have changed in the way the pdf is generated above.

**Comment by ethan92429** [comment]
After a looong look at trying to get Travis to run locally so I could test pdf generation, I decided it was too hard. I tried using travis-build to turn my yaml into a .sh, but I had trouble knowing how to install it, and I tried running Travis locally - which worked, but without travis-build, I can't do much...
