### ISSUE TITLE
Automate textbook publication

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/Textbook#2]
From CEE4540_Master created by [juanchon998](https://github.com/juanchon998) : AguaClara/CEE4540_Master#26  

When the textbook repository is put online, we would like to be able to link to an equation in other documents/pages with pandoc. Also create a "textbook" repo that has only that textbook. Make Pandoc run on Travis CI.

**Comment by ethan92429** [comment]
I think this is done. Now we could add: automated pdf generation, discussion to each page, etc...
