### ISSUE TITLE
Document Errors in the HTML/Latex

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/Textbook#35]
Hi all,

I was just investigating why the textbook didn't build well into a PDF, and I found two errors I'd like to share, both in FCM_Derivations. These might come up again, so I'm documenting the problem in this post. The site built into html, but even there there were visual oddities. 

The first error:
<img width="726" alt="screen shot 2018-07-06 at 09 53 32" src="https://user-images.githubusercontent.com/8585379/42387561-a58b3be0-8110-11e8-8665-4d54df4feef1.png">

The $ sign in front of Q cannot be used! It results in an error that looks like:
`! Missing $ inserted.
<inserted text> 
                $
l.1752 ...k if flow was held constant at \($Q_0\)}` 

when trying to build the PDF. To fix, just remove the dollar sign. If you do want to use the dollar sign in a math block, you must escape it like: `\$'. [Read more on escaping here.](https://latex.org/forum/viewtopic.php?t=5833).

The second error (a bit trickier) was this:
<img width="612" alt="screen shot 2018-07-06 at 09 58 41" src="https://user-images.githubusercontent.com/8585379/42387670-039e4f24-8111-11e8-8adc-e1aa405724ac.png">
Basically, MathJax was trying to find the /cancel package, but couldn't. So I had to make a new way to load MathJax that explicitly adds the cancel extension. [see here.](https://stackoverflow.com/a/51214099/5136799) And here is the relevant 

GitHub link

If this happens again, be sure to include the extension you need in that file. To fix the Latex rendering, which also needed to be pointed explicitly to the 'cancel' package, you need to add the Latex "import" function to the preamble. You can do that here: 

This resulted in the error:
`! Undefined control sequence.
<argument> ...ac {128 \nu L}{g \pi D^4} + \cancel 
                                                  {\frac {8Q}{g \pi ^2 D^4} ...`

Lastly, I saw the following: 
<img width="775" alt="screen shot 2018-07-06 at 10 13 07" src="https://user-images.githubusercontent.com/8585379/42388087-58dc1182-8112-11e8-9a8a-442f3d4e4a5f.png">
Which points to a duck duck go search result. Never use this sort of link! It is highly volatile and will probably change. Click through the link to find the image... I replaced that with : https://www.nuclear-power.net/wp-content/uploads/2016/05/Flow-Regime.png?4b884b. 

The BEST thing to do is to download the image to our site so that we still have it even if nuclear-power goes out of business. General rule of thumb: the longer the URL, the more volatile it is. 

Now these details are quite specific. I don't know if we should document them anywhere... thoughts? I'm thinking we just leave them in this issue and hopefully I've included enough keywords for them to be easily searchable.

**Comment by juanchon998** [comment]
My `make html` -ing didn't catch these, so thank you! I don't think this needs to be documented anywhere but here, I think your explanation is clear enough to serve as a reference in the future. 

I must have been in an off mood not to link to the actual image location... and through duckduckgo nonetheless! How embarrassing. 

Will your solution to adding the 'cancel' package to MathJax work for any other pacakges we may want to use in the future?

**Comment by ethan92429** [comment]
@juanchon998 they wouldn't show up in `make html`... all these errors show up only in `make latex`. I just added `make latex` as something that Travis does, so you'll get online feedback about that!

**Comment by juanchon998** [comment]
Absolutely beautiful! It works great. 

<Random package repository> makes me laugh every time. Thanks!
