### ISSUE TITLE
Website for hosting textbook

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/Textbook#4]
From CEE4540_Master created by [IanCullings](https://github.com/IanCullings) : AguaClara/CEE4540_Master#20  

If you are planning on hosting the textbook on a website, one easy, cheap solution would be to use Github pages.  This allows you to build a website within a repo and host it for free through Github.  There are various levels you could go with this, you could do the HTML and CSS yourself, or use a template such as [this](https://github.com/daattali/beautiful-jekyll) which does a lot of the work for you.  The only cost to using this is purchasing your own domain name, otherwise everything is free

**Comment by ethan92429** [comment]
We are now using gh pages - but specifically a sphinx build completed on Travis. The output is then uploaded to Travis as explained [here.](https://github.com/AguaClara/Textbook/blob/master/README.md) The domain name is https://aguaclara.github.io/Textbook
