### ISSUE TITLE
an index for all the eqn labels and section labels

### ISSUE THREAD

**Issue by clare45** [AguaClara/Textbook#40]
I was looking for a way to find an index of all the label tags within the textbook! (this would make referencing equations much easier because we would know which ones already exist and what we labeled them as)

The simplest thing I found was to use "grep" and a string to search for within a set of files, however that won't work in Windows. and the  other functions that exist in windows (Select-String, and FINSTR) haven't worked for me! 

@ethan92429  do you know any secrets relating to this

**Comment by clare45** [comment]
NVM I got it:

Select-String -Pattern ":label:" -Path "C:\Users\Public\github\Textbook\*\*.rst"

**Comment by clare45** [comment]
I got got by the github...

:label: should be ":label:"

**Comment by ethan92429** [comment]
Cool! It would also be pretty straightforward to write our own addin. I just investigated this and if you need this automated, I could probably do it in about 4 hours.
