### ISSUE TITLE
spell checking in rst

### ISSUE THREAD

**Issue by monroews** [AguaClara/Textbook#48]
Add text.restructuredtext to the List of scopes in the Spell Check package in atom. This will enable spelling checking for rst.
@juanchon998 @clare45

**Comment by ethan92429** [comment]
I just added this to sync settings so that it is changed automatically for anyone who forks my sync settings. [See here. ](https://gist.github.com/ethan92429/8cb1fed2721e41873e9bcb315c804579#file-settings-json-L78)
