### ISSUE TITLE
handling citations 

### ISSUE THREAD

**Issue by clare45** [AguaClara/Textbook#49]
The format of citations of the .md chapters (eg floculation) includes: 

"See the following paper and book respectively for more data on slot width ratios and other hydraulic flocculator parameters: [Haarhoff 1998](http://aqua.iwaponline.com/content/47/3/142 "    DOI: 10.2166/aqua.1998.20"), [Shulz and Okun 1984](https://isbnsearch.org/isbn/0471802611 "ISBN: 0471802611")." 

As well as some hyperlinked references that include the DOI but not as a visible attribute. As far as I've seen now the ability to create a citation in that way doesn't exist  in rst. I am playing with different ways to present citations with direct links and the DOI but we don't yet have convention for that

**Comment by ethan92429** [comment]
First thought is that a hover text is not the best way to convey this info. 

"This is a problem that somebody, somewhere surely has had before..."

And so I went down the road of looking for citation managing. There's a lot of good stuff there. Seems like [sphinxcontrib-bibtex](http://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html) is pretty well established AND uses the very standard [BibTex convention](http://www.bibtex.org/), which is the standard for tex documents.

**Comment by ethan92429** [comment]
@AguaClara/textbook should we now be using BibTex citations as seen here for all things (even external links?)? That would give us the ability to create a full-featured bibliography. Thoughts?

**Comment by ethan92429** [comment]
Thoughts so far: this is not a high priority. All new citations should be created as bibtex citations, and at some point in the future someone will change all the old links to bibtex citations. I added an issue for this.
